### ISSUE TITLE
di-core STM test failure

### ISSUE THREAD

**Issue by roberth** [k0001/di#44]
I've [encountered](https://hydra.nixos.org/build/119231886/nixlog/1) this test failure on hydra

```
  STM:                              FAIL
    test/Main.hs:167:
    expected: 2
     but got: 1
```

It seems like [the test case](https://github.com/k0001/di/blob/master/di-core/test/Main.hs#L157-L167)  could fail when the timestamps are so close that they're "rounded" to the same value.

**Comment by k0001** [comment]
Thanks @roberth. It should be fixed now. Hopefully.

**Comment by k0001** [comment]
Reopening this. The fix was wrong so I reverted it in a9ac00570772372eca39351ff42f61d1afc0063b. The delay should happen within STM.

**Comment by roberth** [comment]
I was unable to make it succeed despite restarting it twice. It's probably a good idea to explicitly check that `"a"` wasn't logged, which seems to be more important than logging two lines.

**Comment by k0001** [comment]
The test that's failing is about making sure that the time when the log
happens is preserved, rather than the time when the STM transaction is
committed. What's happening, as you described, is that clock resolution is
not small enough, so we are not able to distinguish between these two.

I'll probably just unsafely run threadDelay within STM. It's fine for this
testing purpose.

**Comment by k0001** [comment]
Aright, 7a888d0b672e4494213d279e0ebb5a7391dd5016 should have fixed this failing test.
